import projectM3Screenshot1 from '../assets/projects/projectM3Screenshot1.jpg'
import projectM3Screenshot2 from '../assets/projects/projectM3Screenshot2.jpg'
import projectM3Screenshot3 from '../assets/projects/projectM3Screenshot3.jpg'
import projectM3Screenshot4 from '../assets/projects/projectM3Screenshot4.png'

export const P_M3 = {
  title: 'Project: M3 Junction 2 to 4a Asset Verification Task',
  subtitle:
    'Working for WSP and Balfour Beatty, we undertook the task of correctly identifying and recording every asset on the newly rebuilt section of the M3 between junctions 2 and 4a.',
  sections: [
    {
      h: 'Background and objectives',
      p: [
        'Create an assured asset inventory (including line, point, and polygon features) covering every asset above ground on the upgraded M3 corridor between junctions 2 and 4a.',
        'Create the inventory to the specified data dictionary specification, and then configure it for loading into the managing agent’s system.',
        'The data capture was post-construction and was required to develop the asset inventory off-site via a desktop approach.',
      ],
      image: projectM3Screenshot1,
    },
    {
      h: 'Delivery approach',
      p: [
        'AssetScape teamed up with a partner who collected aerial and mobile LiDAR scans, along with aerial ortho-imagery data. The data was automatically loaded into AssetScape, creating the route ready for processing.',
        'The process of data inventory creation was entirely driven by AssetScape’s semi-automated workflow, where assets were first generated by the system and then added to or verified by the processing team. The system enabled the processing team to create, verify, and audit assets within a dedicated data-cleansing module. The module enabled the project manager to track progress, answer questions, and sign off every asset. All decisions were tracked as part of the timeline feature, allowing them to be reviewed at any time.',
        'AssetScape also provided a mobile solution connected to the project’s instance of AssetScape. If required, a survey team could carry out ad-hoc validation of outputs and record any missing or unusual assets (though this was not required).',
      ],
      image: projectM3Screenshot2,
    },
    {
      h: 'Technical detail',
      p: [
        'Mapped aerial LiDAR, orthographic imagery, Google Street View and inherited inventory data within AssetScape.',
        'Identified nearly 45 asset categories using a bespoke identification manual and subject-matter support.',
        'Tracked acceptance, additions, comments and alerts through structured auditing and progress dashboards.',
      ],
      image: projectM3Screenshot3,
    },
    {
      h: 'Outcomes and benefits',
      p: [
        'Issues log and spot-check audit trail provided evidence for National Highways assurance gates.',
        'Clients were provided with access to live outputs on progress via Power BI or Tableau reporting tools.',
        'Created validated data loaders and scripts to ensure compliant data was loaded back to the host system.',
      ],
      image: projectM3Screenshot4,
    },
  ],
  backTo: { pathname: '/', hash: '#projects' },
  backLabel: '← Back to Projects',
  markerLabel: 'Project',
}
