import projectNhRoadLightingScreenshot1 from '../assets/projects/projectNhRoadLightingScreenshot1.png'
import projectNhRoadLightingScreenshot2 from '../assets/projects/projectNhRoadLightingScreenshot2.png'
import projectNhRoadLightingScreenshot3 from '../assets/projects/projectNhRoadLightingScreenshot3.png'
import projectNhRoadLightingScreenshot4 from '../assets/projects/projectNhRoadLightingScreenshot4.png'

export const P_NH_RL = {
  title: 'National Highways Road Lighting',
  subtitle: 'Inventory verification and condition intelligence for lighting assets.',
  sections: [
    {
      h: 'Background and objectives',
      p: 'Delivered a verified lighting inventory with condition intelligence to guide renewal and maintenance planning.',
      image: projectNhRoadLightingScreenshot1,
    },
    {
      h: 'Delivery approach',
      p: [
        'National Highways asked AssetScape to reconcile disparate lighting records and quantify asset condition across the strategic road network.',
        'The process of data invention was entirely created by AssetScape’s semi-automated process, where assets are firstly generated by the system and then added to or verified by the processing team. The system enables the process team to create, verify and audit assets in a specific data cleansing module. The module enables the Project manager to track progress, answer questions and sign off every asset. All decision is tracked as part of the timeline feature, so can be reviewed at any time.',
        'Also provided mobile solution connected to AssetScape’s instance of the project. If required, survey team could carry out ad-hoc validation of output and if required invent any obscure asset inventory (not required).',
      ],
      image: projectNhRoadLightingScreenshot2,
    },
    {
      h: 'Technical detail',
      p: [
        'Fused LiDAR, night-time imagery, existing inventory feeds and site records within AssetScape.',
        'Applied rule-based checks and technician review to validate asset attributes and condition states.',
        'Structured outputs for export into contractor maintenance and design systems.',
      ],
      image: projectNhRoadLightingScreenshot3,
    },
    {
      h: 'Outcomes and benefits',
      p: [
        'Produced prioritised intervention lists backed by traceable evidence packs.',
        'Enabled National Highways lighting teams to evidence funding bids using defensible data.',
      ],
      image: projectNhRoadLightingScreenshot4,
    },
  ],
  backTo: { pathname: '/', hash: '#projects' },
  backLabel: '← Back to Projects',
  markerLabel: 'Project',
}
