import projectHeTechScreenshot1 from '../assets/projects/projectHeTechScreenshot1.png'
import projectHeTechScreenshot2 from '../assets/projects/projectHeTechScreenshot2.png'
import projectHeTechScreenshot3 from '../assets/projects/projectHeTechScreenshot3.png'
import projectHeTechScreenshot4 from '../assets/projects/projectHeTechScreenshot4.png'

export const P_HE_Tech = {
  title: 'National Highways Technology',
  subtitle: 'Data cleansing of technology assets for the whole National Highways technology network.',
  sections: [
    {
      h: 'Background and objectives',
      p: 'Produced a cleansed and reconciled dataset for more than 250,000 roadside technology assets across the North East RCC.',
      image: projectHeTechScreenshot1,
    },
    {
      h: 'Delivery approach',
      p: [
        'National Highways technology team required sub-metre accurate locations and condition intelligence to underpin operations and maintenance contracts.',
        'The process of data invention was entirely created by AssetScape’s semi-automated process, where assets are firstly generated by the system and then added to or verified by the processing team. The system enables the process team to create, verify and audit assets in a specific data cleansing module. The module enables the Project manager to track progress, answer questions and sign off every asset. All decision is tracked as part of the timeline feature, so can be reviewed at any time.',
        'Also provided mobile solution connected to AssetScape’s instance of the project. If required, survey team could carry out ad-hoc validation of output and if required invent any obscure asset inventory (not required).',
      ],
      image: projectHeTechScreenshot2,
    },
    {
      h: 'Technical detail',
      p: [
        'Combined AVIS and OS imagery, LiDAR point clouds and OS mapping within a tailored AssetScape schema.',
        'Applied point-cloud feature recognition and 3D visualisation to digitise equipment to within less than a metre.',
        'Implemented structured processing methodology, audit protocols and output specifications for downstream systems.',
      ],
      image: projectHeTechScreenshot3,
    },
    {
      h: 'Outcomes and benefits',
      p: [
        'Delivered assurance packs with traceable edits and review history for National Highways governance.',
        'Enabled technology service providers to plan interventions using a single, trusted source of asset data.',
      ],
      image: projectHeTechScreenshot4,
    },
  ],
  backTo: { pathname: '/', hash: '#projects' },
  backLabel: '← Back to Projects',
  markerLabel: 'Project',
}
