import projectNhRoadLightingScreenshot1 from '../assets/projects/projectNhRoadLightingScreenshot1.png'
import projectNhRoadLightingScreenshot2 from '../assets/projects/projectNhRoadLightingScreenshot2.png'
import projectNhRoadLightingScreenshot3 from '../assets/projects/projectNhRoadLightingScreenshot3.png'
import projectNhRoadLightingScreenshot4 from '../assets/projects/projectNhRoadLightingScreenshot4.png'

export const P_NH_RL = {
  title: 'National Highways Road Lighting',
  subtitle: 'Inventory verification and condition intelligence for lighting assets.',
  sections: [
    {
      h: 'Background and objectives',
      p: 'We delivered a verified lighting inventory with condition intelligence to guide renewal and maintenance planning.',
      image: projectNhRoadLightingScreenshot1,
    },
    {
      h: 'Delivery approach',
      p: [
        'National Highways asked AssetScape to reconcile disparate lighting records and quantify asset condition across the strategic road network.',
        'The process of data inventory creation was entirely driven by AssetScape’s semi-automated workflow, where assets were first generated by the system and then added to or verified by the processing team. The system enabled the processing team to create, verify, and audit assets within a dedicated data-cleansing module. The module enabled the project manager to track progress, answer questions, and sign off every asset. All decisions were tracked as part of the timeline feature, allowing them to be reviewed at any time.',
        'Provided a mobile solution connected to the project’s instance of AssetScape, enabling the survey team to carry out ad-hoc validation of outputs and record any missing or unusual assets when required (though this was not necessary during the project).',
      ],
      image: projectNhRoadLightingScreenshot2,
    },
    {
      h: 'Technical detail',
      p: [
        'Fused LiDAR, night-time imagery, existing inventory feeds and site records within AssetScape.',
        'Applied rule-based checks and technician review to validate asset attributes and condition states.',
        'Structured outputs for export into contractor maintenance and design systems.',
      ],
      image: projectNhRoadLightingScreenshot3,
    },
    {
      h: 'Outcomes and benefits',
      p: [
        'Produced prioritised intervention lists backed by traceable evidence packs.',
        'Enabled National Highways lighting teams to evidence funding bids using defensible data.',
      ],
      image: projectNhRoadLightingScreenshot4,
    },
  ],
  backTo: { pathname: '/', hash: '#projects' },
  backLabel: '← Back to Projects',
  markerLabel: 'Project',
}
